<a href="https://colab.research.google.com/github/HRISHI-26/Machine-Learning-Notebooks/blob/main/Linear_Algebra_Assignments.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Linear Algebra Assignments

1. Solve a set of problems involving vector and matrix operations.
2. Submit a Jupyter Notebook with calculations of eigenvalues and eigenvectors for a given matrix.

## Vector Operations - Using List

1. Basic vector and matrix operations

In [ ]:
vector_a = [1, 2, 3, 4, 5]
vector_b = [10, 20, 30, 40, 50]

scalar = 10

In [ ]:
# Addition
vector_sum = []

for i in range(len(vector_a)):
    vector_sum.append(vector_a[i] + vector_b[i])

print("Sum:", vector_sum)

Sum: [11, 22, 33, 44, 55]


In [ ]:
# Substraction
vector_diff = []

for i in range(len(vector_a)):
  vector_diff.append(vector_a[i] - vector_b[i])

print("Difference:", vector_diff)

Difference: [-9, -18, -27, -36, -45]


In [ ]:
# Scalar Multiplication

vector_spdt = []

for i in range(len(vector_a)):
  vector_spdt.append(vector_a[i] * scalar)

print("Scalar Product:", vector_spdt)

Scalar Product: [10, 20, 30, 40, 50]


##Vector Operations - Using Numpy Array

In [ ]:
import numpy as np

In [ ]:
vector_a_np = np.array(vector_a)
vector_b_np = np.array(vector_b)

In [ ]:
# Addition
vector_sum = vector_a_np + vector_b_np
print("Sum:", vector_sum)

vector_sum = np.add(vector_a_np, vector_b_np)
print("Sum:", vector_sum)

Sum: [11 22 33 44 55]
Sum: [11 22 33 44 55]


In [ ]:
# Substraction
vector_diff = vector_a_np - vector_b_np
print("Difference:", vector_diff)

vector_diff = np.subtract(vector_a_np, vector_b_np)
print("Difference:", vector_diff)

Difference: [ -9 -18 -27 -36 -45]
Difference: [ -9 -18 -27 -36 -45]


In [ ]:
#  Scalar Multiplication
scalar = 25

vector_spdt = vector_a_np * scalar
print("Scalar Product:", vector_spdt)

vector_spdt = np.multiply(vector_a_np, scalar)
print("Scalar Product:", vector_spdt)

Scalar Product: [ 25  50  75 100 125]
Scalar Product: [ 25  50  75 100 125]


##Matrix Operations - Using List

In [ ]:
matrix_a = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

matrix_b = [
    [2, 4, 6],
    [3, 6, 9],
    [4, 8, 12]
]

In [ ]:
# Addition
matrix_sum = []
for i in range(len(matrix_a)): # i: 0 1 2
  row = []
  for j in range(len(matrix_a[0])): # j: 0, 1, 2
    row.append(matrix_a[i][j] + matrix_b[i][j])
  matrix_sum.append(row)

print("Sum:", matrix_sum)

Sum: [[3, 6, 9], [7, 11, 15], [11, 16, 21]]


In [ ]:
# Substraction
matrix_diff = []
for i in range(len(matrix_a)):
  row = []
  for j in range(len(matrix_a[0])):
    row.append(matrix_a[i][j] - matrix_b[i][j])
  matrix_diff.append(row)

print("Difference:", matrix_diff)

Difference: [[-1, -2, -3], [1, -1, -3], [3, 0, -3]]


In [ ]:
# Multiplication

matrix_pdt = []
for i in range(len(matrix_a)):
  row = []
  for j in range(len(matrix_a[0])):
    pdt_sum = 0
    for k in range(len(matrix_b)):
      pdt_sum += matrix_a[i][k] * matrix_b[k][j]
    row.append(pdt_sum)
  matrix_pdt.append(row)

print("Product:",matrix_pdt)

Product: [[20, 40, 60], [47, 94, 141], [74, 148, 222]]


In [ ]:
# Transpose

for i in range(len(matrix_a)):
  for j in range(len(matrix_a)):
    if i < j:
      matrix_a[i][j],matrix_a[j][i]=matrix_a[j][i],matrix_a[i][j]

print(matrix_a)

[[1, 4, 7], [2, 5, 8], [3, 6, 9]]


In [ ]:
# Scalar Multiplication with matrix

scalar = 20
matrix_a = [
    [1, 2, 3],
    [2, 4, 6],
    [9, 4, 5]
]

matrix_spdt = []

for i in range(len(matrix_a)):
  row = []
  for j in range(len(matrix_a[0])):
    row.append(scalar * matrix_a[i][j])
  matrix_spdt.append(row)

print("Scalar Product: ", matrix_spdt)

Scalar Product:  [[20, 40, 60], [40, 80, 120], [180, 80, 100]]


##Matrix operations - Using Numpy Array

In [ ]:
matrix_a = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

matrix_b = [
    [2, 4, 6],
    [3, 6, 9],
    [4, 8, 12]
]

matrix_a_np = np.array(matrix_a)
matrix_b_np = np.array(matrix_b)

In [ ]:
# Addition
print("Sum:",matrix_a_np + matrix_b_np)
print("Sum:",np.add(matrix_a_np,matrix_b_np))

Sum: [[ 3  6  9]
 [ 7 11 15]
 [11 16 21]]
Sum: [[ 3  6  9]
 [ 7 11 15]
 [11 16 21]]


In [ ]:
# Substraction
print("Sum:",matrix_a_np - matrix_b_np)
print("Sum:",np.subtract(matrix_a_np,matrix_b_np))

Sum: [[-1 -2 -3]
 [ 1 -1 -3]
 [ 3  0 -3]]
Sum: [[-1 -2 -3]
 [ 1 -1 -3]
 [ 3  0 -3]]


In [ ]:
# Transpose
print("Sum:",matrix_a_np.T)
print("Sum:",np.transpose(matrix_a_np))

Sum: [[1 4 7]
 [2 5 8]
 [3 6 9]]
Sum: [[1 4 7]
 [2 5 8]
 [3 6 9]]


In [ ]:
# Scalar Multiplication
scalar = 25

print("Scalar Product:", scalar * matrix_a_np)
print("Scalar Product:", np.multiply(scalar, matrix_a_np))

Scalar Product: [[ 25  50  75]
 [100 125 150]
 [175 200 225]]
Scalar Product: [[ 25  50  75]
 [100 125 150]
 [175 200 225]]


In [ ]:
# Matrix Multiplication

# Dot product and matrix multiplication are sometimes samedepending upon dimension

print("Product: ", np.matmul(matrix_a_np, matrix_b_np))

print("Dot Product: ", np.dot(matrix_a_np, matrix_b_np))
print("Dot Product: ", matrix_a_np @ matrix_b_np)

Product:  [[ 20  40  60]
 [ 47  94 141]
 [ 74 148 222]]
Dot Product:  [[ 20  40  60]
 [ 47  94 141]
 [ 74 148 222]]
Dot Product:  [[ 20  40  60]
 [ 47  94 141]
 [ 74 148 222]]


##Calculating Eigen values and Eigen vectors - Using List

In [ ]:
import math

In [ ]:
#  Solving Equations
# 3x + 5y = 10
# 2x + 6y = 6

matrix = [[3, 5],[2, 6]]

def find_eigen(matrix):
  a, b = matrix[0]
  c, d = matrix[1]

  trace = a + d
  determinent = a*d - b*c

  discriminant = trace**2 - 4*determinent

  if discriminant < 0:
        return "Complex value....."
  sqrt_desc = math.sqrt(discriminant)

  lambda1 = (trace + sqrt_desc)/2
  lambda2 = (trace - sqrt_desc)/2

  eigenvalue = [lambda1, lambda2]

  eigenvector = []

  for lam in eigenvalue:
    A_minus_lambda_I = [
        [a-lam, b],
        [c, d-lam]
    ]

    if b != 0:
      x = -(a-lam) / b
      eigenvector.append([x, 1])
    elif c != 0:
      y = -(d-lam) / c
      eigenvector.append([1, y])
    else:
      eigenvector.append([1, 0])

  return eigenvalue, eigenvector

eigenvalue, eigenvector = find_eigen(matrix)
print("Eigen values: ", eigenvalue)
print("Eigen vector: ", eigenvector)

Eigen values:  [8.0, 1.0]
Eigen vector:  [[1.0, 1], [-0.4, 1]]
