In [1]:
import numpy as np

my_arr = np.arange(1_000_000)

my_list = list(range(1_000_000))

print(my_arr)

[     0      1      2 ... 999997 999998 999999]


In [2]:
%timeit my_arr2 = my_arr * 2

%timeit my_list2 = [x * 2 for x in my_list]

1.15 ms ± 12.2 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
37.5 ms ± 196 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [3]:
arr = np.identity(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [4]:

a = np.identity(10, dtype='bool')
print(a)

[[ True False False False False False False False False False]
 [False  True False False False False False False False False]
 [False False  True False False False False False False False]
 [False False False  True False False False False False False]
 [False False False False  True False False False False False]
 [False False False False False  True False False False False]
 [False False False False False False  True False False False]
 [False False False False False False False  True False False]
 [False False False False False False False False  True False]
 [False False False False False False False False False  True]]


In [5]:
new = np.arange(10)

print(new)

[0 1 2 3 4 5 6 7 8 9]


In [46]:
import pandas as pd

data = pd.Series([2,4,6,8,8,8,4,4,4])
print(data)
print(data.describe())
data.groupby(data)
# print(data.median())




df = pd.DataFrame({'Animal': ['Falcon', 'Falcon',
                              'Parrot', 'Parrot'],
                   'Max Speed': [380., 370., 24., 26.]})

df.groupby(['Animal'])

0    2
1    4
2    6
3    8
4    8
5    8
6    4
7    4
8    4
dtype: int64
count    9.000000
mean     5.333333
std      2.236068
min      2.000000
25%      4.000000
50%      4.000000
75%      8.000000
max      8.000000
dtype: float64


In [12]:
hello = np.eye(3)
print(hello)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [55]:
# List

arr = [19, 20, 33, 40, 51, 20]

# Print each element of a list using a for loop
for i in arr:
    print(i)
print("-------------------------------------")

# Print only the even numbers from a list.
for i in arr:
    if i%2 == 0:
        print(i)

print("-------------------------------------")
# Calculate the sum of all elements in a list.
sum(arr)
print("-------------------------------------")

# Count how many times a particular number (e.g., 5) appears in a list.
arr.count(20)

print("-------------------------------------")
# Create a new list with the squares of numbers from 1 to 10 using list comprehension.

new = [i**2 for i in arr]
print(new)
print("-------------------------------------")

# From a list of numbers, create a new list that contains only the odd numbers.
new = [i for i in arr if i%2 != 0]
print(new)
print("-------------------------------------")



19
20
33
40
51
20
-------------------------------------
20
40
20
-------------------------------------
-------------------------------------
-------------------------------------
[361, 400, 1089, 1600, 2601, 400]
-------------------------------------
[19, 33, 51]


In [75]:
# Create a 2D list (matrix) with 3 rows and 3 columns filled with numbers.

matrix = [
    [1,2,3],
    [2,4,6],
    [3,6,9]
]

# Access the element at row 2, column 3 of a 2D list.
print(matrix[1][2])
print("-------------------------------------")


# Write a program to print each row of a 2D list using nested loops.
for i in matrix:
    print(i)
print("-------------------------------------")

# Calculate the sum of each row in a 2D list.
for i in matrix:
    print(sum(i))
print("-------------------------------------")

# Flatten a 2D list into a 1D list.
listed = []
for i in matrix:
    for j in i:
        listed.append(j)
print(listed)
print("-------------------------------------")

listed = [j for i in matrix for j in i]
print(listed)
print("-------------------------------------")

# Sort a list in ascending and descending order.
for i in range(0,len(listed)-1):
    for j in range(i,len(listed)):
        if listed[i] > listed[j]:
            listed[i], listed[j] = listed[j], listed[i]

print(listed)

for i in range(0,len(listed)-1):
    for j in range(i,len(listed)):
        if listed[i] < listed[j]:
            listed[i], listed[j] = listed[j], listed[i]
print(listed)

6
-------------------------------------
[1, 2, 3]
[2, 4, 6]
[3, 6, 9]
-------------------------------------
6
12
18
-------------------------------------
[1, 2, 3, 2, 4, 6, 3, 6, 9]
-------------------------------------
[1, 2, 3, 2, 4, 6, 3, 6, 9]
-------------------------------------
[1, 2, 2, 3, 3, 4, 6, 6, 9]
[9, 6, 6, 4, 3, 3, 2, 2, 1]


In [79]:
# Remove duplicates from a list.
dupe = set(listed)
listed = list(dupe)
print(listed)

# Merge two lists into one.
new = listed + arr
print(new)

# Find the maximum and minimum element in a list.
print(max(new))
print(min(new))

[1, 2, 3, 4, 6, 9]
[1, 2, 3, 4, 6, 9, 19, 20, 33, 40, 51, 20]
51
1


In [82]:
# Replace all negative numbers in a list with 0.

arr = [1,2,3,4,5,-1,-2,-3,-4,-5]

# <list_name> = [<exppression> if <condition> else <expression> for <variable> in <collection>]
arr = [-1 if i < 0 else i for i in arr]
print(arr)

[1, 2, 3, 4, 5, -1, -1, -1, -1, -1]


In [85]:

new = [i for i in arr if i%2 == 0]
print(new)

new = [i**2 for i in arr if i%2==1 and i > 0]
print(new)


[2, 4]
[1, 9, 25]


In [95]:
nums = [10, 20, 30, 40, 50]

# update the value at index 2 to 100
nums[2] = 100
print(nums)

# Swap the first and last elements of a list.
nums[0], nums[-1] = nums[-1], nums[0]
print(nums)

# Check if a number 25 exists in a list.
print(25 in nums)

# Write a program to find the index of a given element in a list.
check = int(input("Enter an element: "))
index = nums.index(check)
print(index)

# Write a function that returns all numbers greater than 50 from a list.
new = [i for i in nums if i > 50]
print(new)

# Write a function to find the second largest number in a list.
max = 0
for i in nums:
    if i > max:
        premax = max
        max = i

print(premax)


# Given a list of strings, return only the strings that start with "a".
names = ["alan", "basil", "helen", "boby", "robin", "akhila"]
wprint([i for i in names if i.startswith("a")])

[10, 20, 100, 40, 50]
[50, 20, 100, 40, 10]
False


Enter an element:  20


1
[100]
50
['alan', 'akhila']
