In [1]:
import numpy as np

In [2]:
from time import process_time

In [3]:
python_list = [i for i in range(100000)]

start_time = process_time()

python_list = [i+5 for i in python_list]

end_time = process_time()

print(end_time - start_time)

0.004081999999999919


In [4]:
np_array = np.array([i for i in range(100000)])

start_time = process_time()

np_array += 5

end_time = process_time()

print(end_time - start_time)

0.00013199999999979894


In [5]:
# List

list1 = [1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [6]:
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [7]:
# Creating a 1 Dimentional array

a = np.array([1,2,3,4,5])
print(a)
print(a.shape)

[1 2 3 4 5]
(5,)


In [8]:
b = np.array([(1,2,3,4,5),(6,7,8,9,0)])
print(b)
print(b.shape)

[[1 2 3 4 5]
 [6 7 8 9 0]]
(2, 5)


In [9]:
c = np.array([(1,2,3,4),(5,6,7,8)], dtype=float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


In [10]:
# Create a numpy array of zeros
x = np.zeros((4,5)) #Array of 0
print(x)
y = np.ones((3,3)) #Array of 1
print(y)
z = np.full((5,4), 6) #Array of specified element
print(z)
i = np.eye(4) #Identity matrix of given order 
print(i)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [11]:
# Creating numpy arrays with random values
r = np.random.random((2,2)) # Random values b/w 0 and 1
print(r)

# Creating array of integers within a range
ir = np.random.randint(10, 20, (3,4))
print(ir)

[[0.71675251 0.56557484]
 [0.72830807 0.19863524]]
[[17 12 13 16]
 [10 16 18 16]
 [12 11 14 14]]


In [12]:
# Creating array of evenly spaced values -> dividing into parts
d = np.linspace(10, 20, 6)
print(d)

# Creating array of evenly spaced values -> steps
sd = np.arange(0, 10, 3)
print(sd)

[10. 12. 14. 16. 18. 20.]
[0 3 6 9]


In [13]:
# Convertion of list or tuple
list2 = [10,20,30,40,50,60]

np_array2 = np.asarray(list2)
print(np_array2)
type(np_array2)

[10 20 30 40 50 60]


numpy.ndarray

In [14]:
# Analysing a numpy array

c = np.random.randint(10, 90, (5,5))
print(c)

print(c.shape)  #order
print(c.dtype)  #datatype
print(c.ndim)   #dimention
print(c.size)   #no: of elements

[[81 55 71 23 15]
 [80 62 47 79 78]
 [80 30 58 29 21]
 [77 87 75 52 41]
 [38 59 23 15 42]]
(5, 5)
int64
2
25


In [15]:
# " + " in list

list_1 = [1,2,3,4,5]
list_2 = [6,7,8,9,10]
print(list_1 + list_2) #concatenation '+' in list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [16]:
# Mathemetical operations on an Numpy Array

np_array_1 = np.random.randint(0,10, (3,3))
np_array_2 = np.random.randint(0,10, (3,3))

print(np_array_1)
print(np_array_2)

print(np_array_1 + np_array_2) # addition '+'
print(np_array_1 - np_array_2) # substraction '-'
print(np_array_1 * np_array_2) # multiplication '*'
print(np_array_1 / np_array_2) # division '/'

# ---------------------------------------------------------

print(np.add(np_array_1, np_array_2))
print(np.subtract(np_array_1, np_array_2))
print(np.multiply(np_array_1, np_array_2))
print(np.divide(np_array_1, np_array_2))

[[4 7 2]
 [3 5 8]
 [2 0 2]]
[[3 1 6]
 [3 4 2]
 [5 0 2]]
[[ 7  8  8]
 [ 6  9 10]
 [ 7  0  4]]
[[ 1  6 -4]
 [ 0  1  6]
 [-3  0  0]]
[[12  7 12]
 [ 9 20 16]
 [10  0  4]]
[[1.33333333 7.         0.33333333]
 [1.         1.25       4.        ]
 [0.4               nan 1.        ]]
[[ 7  8  8]
 [ 6  9 10]
 [ 7  0  4]]
[[ 1  6 -4]
 [ 0  1  6]
 [-3  0  0]]
[[12  7 12]
 [ 9 20 16]
 [10  0  4]]
[[1.33333333 7.         0.33333333]
 [1.         1.25       4.        ]
 [0.4               nan 1.        ]]


/var/folders/7_/x4pp4kc13qv5t27q0p9t_nkh0000gn/T/ipykernel_80051/2336386358.py:12: RuntimeWarning: invalid value encountered in divide
  print(np_array_1 / np_array_2) # division '/'
/var/folders/7_/x4pp4kc13qv5t27q0p9t_nkh0000gn/T/ipykernel_80051/2336386358.py:19: RuntimeWarning: invalid value encountered in divide
  print(np.divide(np_array_1, np_array_2))


In [20]:
# Array Manipulation

arr = np.random.randint(0, 10, (2,3))
print(arr)
print(arr.shape)

# Transpose - 2 methods
print(arr.T)
print(np.transpose(arr))

# Reshaping 
re_arr = np.reshape(arr, (1,6))
print(re_arr)
re_arr = np.reshape(arr, (6,1))
print(re_arr)

[[6 4 9]
 [2 2 5]]
(2, 3)
[[6 2]
 [4 2]
 [9 5]]
[[6 2]
 [4 2]
 [9 5]]
[[6 4 9 2 2 5]]
[[6]
 [4]
 [9]
 [2]
 [2]
 [5]]
