In [1]:
# Numpy  = Numerical Python
# Related to multidimensional arrays

# FEATURES
    # Speed
    # Large Homogenous Data Handling
    # Reduced Memory Consumption

# 0-d -> Scalar
# 1-d -> Vector
# 2-d -> Matrix
# N-d -> Tensor

# Restrictions:
    # Homogenous Data 
    # Immutable Element Size
    # Rectangular Shape

# DIMENSION = AXIS


In [2]:
# Importing
import numpy as np

# Array Initialization
a = np.array([1, 2, 3, 4, 5])
b = np.array([
    [1, 2, 3, 4],
    [0, 9, 8, 7],
    [2, 4, 6, 7],
])

print(a)
print(b)

[1 2 3 4 5]
[[1 2 3 4]
 [0 9 8 7]
 [2 4 6 7]]


In [3]:
# Accessing numpy arrays

print(a[0])
print(a[-1])
print(a[:2])
print(a[2:])

1
5
[1 2]
[3 4 5]


In [4]:
print(b[0,0])
print(b[0,0:])

1
[1 2 3 4]


In [5]:
# Attributes of Array

# To Get Dimension or Axis
print(a.ndim)
print(b.ndim)

# To Get Order of Array
print(a.shape)
print(b.shape)

# To get Total No of elements
print(a.size)
print(b.size)

# To get Datatype of Array
print(a.dtype)
print(b.dtype)

1
2
(5,)
(3, 4)
5
12
int64
int64


In [6]:
# Basic Array Types

    # Array of Zero's
print(np.zeros(5))
    # Array of One's
print(np.ones(5))
    # Array of Random Values
print(np.empty(2))
    # Array of first 'n' whole numbers
print(np.arange(5))
    # Array from i - f spaced evenly (common difference)
print(np.linspace(10, 25, num=5))


    # Array of Ones with dtype specified
print(np.ones(5, dtype=int))


[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[ 5.55251295e-238 -9.30742058e-218]
[0 1 2 3 4]
[10.   13.75 17.5  21.25 25.  ]
[1 1 1 1 1]


In [15]:
# Basic Operations
# Sort and Concatenate

# Sorting
arr = np.empty(2)
print(arr)
np.sort(arr)


# Concatenating
ar = np.array([1, 2, 3])
br = np.array([4, 5, 6])

print(np.concatenate((ar, br)))

[5.55251295e-238 9.30742058e-218]
[1 2 3 4 5 6]


In [20]:
# A Basic Example of 3 dimensional array

array_example = np.array([[
    [1,2,3,4],
    [2,4,6,8],],
    [[10, 20, 30, 40],
     [20, 40, 60, 80]],
    [[100, 200, 300, 400],
     [200, 400, 600, 800]] ])

print(array_example.dtype)
print(array_example.ndim)
print(array_example.shape)
print(array_example.size)

int64
3
(3, 2, 4)
24


In [25]:
# Reshaping an Array

print(array_example.reshape(4,6))

print(array_example.reshape(2,12))

[[  1   2   3   4   2   4]
 [  6   8  10  20  30  40]
 [ 20  40  60  80 100 200]
 [300 400 200 400 600 800]]
[[  1   2   3   4   2   4   6   8  10  20  30  40]
 [ 20  40  60  80 100 200 300 400 200 400 600 800]]
