In [1]:
# 1. Introduction to Linear Algebra

In [2]:
# DATA = collection of features = VECTOR
# Values of each feature represents magnitude
# Each feature is a Dimension (direction)

# A DATASET IS ITSELF A MATRIX

# MODEL FITTING:  If a "transformation matrix" is applied to DATASET

# After model fitting we get "predicted output" - This is "NEW VECTOR"

# =============================================================================================


# dataset is a collection of vectors in an n-dimensional vector space, where n = number of features.
# The model learns a matrix that projects data from the full vector space (ℝ¹⁰) into a subspace (ℝ²).

# vector space -----------> PCA ------------> sub space -------> model fitting



# ==============================================================================================

            # | Term         | In Simple Words                                     |
            # | ------------ | --------------------------------------------------- |
            # | Vector Space | Full feature space (all possible data vectors)      |
            # | Vector       | One data point                                      |
            # | Dataset      | Collection of vectors → forms the vector space      |
            # | Matrix       | Applies transformations in/from vector spaces       |
            # | Subspace     | Lower-dimensional space the model projects into     |
            # | Model        | Learns or uses subspaces for compression/prediction |

# ==============================================================================================

# Your original dataset has 10 features → so each data point is a vector in ℝ¹⁰
# 👉 This means the full vector space is ℝ¹⁰

# But during training, you use only 5 features (due to their predictive power or feature selection)
# 👉 Now, you're working in a 5-dimensional subspace, a part of ℝ¹⁰

# ==============================================================================================

# PCA will analyze the redundancies across features, and if two or more features
# contain similar patterns or data, it will optimize by combining them into a single
# principal component, which best represents their shared variation.

# ==============================================================================================

        # | Step | What Happens          | Why It Matters                      |
        # | ---- | --------------------- | ----------------------------------- |
        # | 1️⃣   | Subtract mean         | Normalize the center of data        |
        # | 2️⃣   | Covariance matrix     | See feature relationships           |
        # | 3️⃣   | Eigenvectors & values | Find directions of variance         |
        # | 4️⃣   | Keep top eigenvectors | Capture most variance (info)        |
        # | 5️⃣   | Project data          | Get reduced features (e.g., 2D, 3D) |

# ==============================================================================================

        # | Covariance Value | Meaning                                   |
        # | ---------------- | ----------------------------------------- |
        # | > 0              | Features increase together (positive)     |
        # | < 0              | One increases, other decreases (negative) |
        # | = 0              | Features are unrelated (independent)      |

# ==============================================================================================

# ✅ Refined Statement:
# Each value in an eigenvector represents how much each original feature contributes to the new axis 
# (principal component), regardless of whether features are redundant or not.
# In PCA, redundant features will tend to contribute together to the same component, because they share variance.

# | Concept                       | Meaning                                                                   |
# | ----------------------------- | ------------------------------------------------------------------------- |
# | **Eigenvector**               | A new axis (principal component)                                          |
# | **Each value in eigenvector** | Contribution of each original feature                                     |
# | **Redundant features**        | Tend to have **similar weights** in the same eigenvector                  |
# | **PCA**                       | Uses eigenvectors to combine features into fewer, uncorrelated components |


# When a transformation is applied, some vectors end up staying in the same position. These vectors are 
# called eigenvectors. The factor by which eigenvectors are scaled after the transformation is called eigenvalues.

# ==============================================================================================



In [3]:
# A scalar value only possess magnitude
scalar = 10
print("Scalar: " + str(scalar))

Scalar: 10


In [4]:
# A vector has a magnitude and a direction 
# (x-axis)
# A vector can be represented in a 1D array or list

# Using list
vector = [1, 2, 3, 4, 5]
print("Python:: Vector: ", vector)

# Using numpy array
import numpy as np

vector_np = np.array(vector)
print("Numpy::  Vector: ", vector_np)

Python:: Vector:  [1, 2, 3, 4, 5]
Numpy::  Vector:  [1 2 3 4 5]


In [5]:
# A matrix is a 2D which consists of different vectors
# (x-axis and y-axis)
# A matrix can be represented as 2D list or array

# Using list
matrix = [
    [1, 2],
    [3, 4]
]
print("Python Matrix: ", matrix)

# Using numpy array
matrix_np = np.array(matrix)
print("Numpy  Matrix: ", matrix_np)

Python Matrix:  [[1, 2], [3, 4]]
Numpy  Matrix:  [[1 2]
 [3 4]]


In [6]:
                        # Basic Vector Operations
# Addition, Substraction, Scalar Multiplication

                # Addition
# Using List
vector_a = [1, 2, 3, 4, 5]
vector_b = [2, 4, 6, 8, 10]
vector_sum = []
for i in range(len(vector_a)):
    vector_sum.append(vector_a[i] + vector_b[i]) 

print("Sum using List:  ", vector_sum)

# Using numpy array
vector_a_np = np.array(vector_a)
vector_b_np = np.array(vector_b)

vector_sum_np = vector_a_np + vector_b_np
print("Sum using '+':   ", vector_sum_np)

vector_sum_np = np.add(vector_a_np, vector_b_np)
print("Sum using add(): ", vector_sum_np)

Sum using List:   [3, 6, 9, 12, 15]
Sum using '+':    [ 3  6  9 12 15]
Sum using add():  [ 3  6  9 12 15]


In [7]:
            # Substraction
# Using List
vector_diff = []
for i in range(len(vector_a)):
    vector_diff.append(vector_a[i] - vector_b[i])

print("Difference using List:       ", vector_diff)

# Using numpy array
vector_diff = vector_a_np - vector_b_np
print("Difference using '-':        ", vector_diff)

vector_diff = np.subtract(vector_a_np, vector_b_np)
print("Difference using subtract(): ", vector_diff)

Difference using List:        [-1, -2, -3, -4, -5]
Difference using '-':         [-1 -2 -3 -4 -5]
Difference using subtract():  [-1 -2 -3 -4 -5]


In [8]:
        # Scalar Multiplication

vector_a = [1, 2, 3, 4, 5]
vector_a_np = np.array(vector_a)

scalar = 10
vector_spdt = []


# Using List
for i in range(len(vector_a)):
    vector_spdt.append(vector_a[i] * scalar)

print("Scalar product using List:        ", vector_spdt)

# Using numpy array
vector_spdt = scalar * vector_a_np
print("Scalar product using '*':         ", vector_spdt)

vector_spdt = np.multiply(scalar, vector_a_np)
print("Scalar product using multiply():  ", vector_spdt)

Scalar product using List:         [10, 20, 30, 40, 50]
Scalar product using '*':          [10 20 30 40 50]
Scalar product using multiply():   [10 20 30 40 50]


In [9]:
# Scalar multiplication of 2D matrix

s_matrix = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
scalar = 10

matrix_pdt = []
for i in range(len(s_matrix)):
    row = []
    for j in range(len(s_matrix[i])):
        element = scalar * s_matrix[i][j]
        row.append(element)
    matrix_pdt.append(row)

print("Scalar Product of 2D matrix: ", matrix_pdt)

Scalar Product of 2D matrix:  [[10, 20, 30], [40, 50, 60], [70, 80, 90]]


In [10]:
# 2. Vectors and Matrices

# Vector Space: 
# It is a collection of vectors and all possible linear combinations of these vectors.
# It also contains operations or rules of vector addition and scalar multiplication.

# Sub Space:
# It is a subset of vector space, where it should contain:
# > Zero vector
# > All same Vector addition
# > All same Scalar multiplication

# Subspace = Subset( Vector Space) under Vector Addition, Scalar Multiplication and Zero Vector

In [11]:
# Types of Matrices

# 1. Singleton matrix       - 1 element
a = [1]
# 2. Row matrix             - 1 row
a = [1, 2, 3, 4, 5]
# 3. Column matrix          - 1 column
a = [[1], [2], [3]]

# 4. Singular matrix        - Inverse exist
# 5. NonSingular matrix     - Inverse does'nt exist

# 6. Square matrix          - row = column
a = [[1, 2], [3, 4]]
# 7. Rectangular matrix     - row != column
a = [[1, 2, 3], [1, 2, 3]]

# 8. Zero/Null matrix       - Full Zeros
a = [[0, 0], [0, 0]]
# 9. Identiy matrix         - Diagonal 1 
a = [[1, 0], [0, 1]]
# 10. Diagonal matrix       - Diagonal elements are random
a = [[2, 0], [0, 5]]
# 11. Scalar matrix         - Diagonal elements are same
a = [[5, 0], [0, 5]]

# 12. Sparse matrix         - More 0's 
a = [[0, 0, 1], [10, 0, 0], [0, 23, 0]]
# 13. Dense matrix          - Less or No 0's
a = [[0, 93, 1], [10, 74, 0], [9, 23, 1]]

# 14. Upper Triangular      - Non zero @ above diagonal
a = [[2, 93, 1], [0, 74, 10], [0, 0, 1]]
# 15. Lower Triangular      - Non zero @ below diagonal
a = [[2, 0, 0], [10, 74, 0], [8, 30, 1]]

# 16. Orthogonal matrix     - A • A•T = I

# 17. Symmetric matrix      - A = (A•T)
a = [[1, 2, 3], [2, 3, 1], [3, 1, 2]]
# 18. Skew Symmetric matrix - (-A) = (A•T)
a = [[1, -2, -3], [2, 3, -1], [3, 1, 2]]

In [12]:
# Matrix Operations

            # Addition
matrix_a = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
matrix_b = [
    [2, 4, 6],
    [8, 10, 12],
    [14, 16, 18]
]
    
# Using list
matrix_sum = []
for i in range(len(matrix_a)):
    row = []
    for j in range(len(matrix_a[0])):
        row.append(matrix_a[i][j] + matrix_b[i][j])
    matrix_sum.append(row)

print("Sum of Matrix using list:  ", matrix_sum)


matrix_a_np = np.array(matrix_a)
matrix_b_np = np.array(matrix_b)

# Using numpy array
matrix_sum = matrix_a_np + matrix_b_np
print("Sum of Matrix using '+':   ", matrix_sum)

matrix_sum = np.add(matrix_a_np, matrix_b_np)
print("Sum of Matrix using add(): ", matrix_sum)


Sum of Matrix using list:   [[3, 6, 9], [12, 15, 18], [21, 24, 27]]
Sum of Matrix using '+':    [[ 3  6  9]
 [12 15 18]
 [21 24 27]]
Sum of Matrix using add():  [[ 3  6  9]
 [12 15 18]
 [21 24 27]]


In [13]:
#         # Subtraction
# # Using list
matrix_diff = []
for i in range(len(matrix_a)):
    row = []
    for j in range(len(matrix_a[0])):
        row.append(matrix_a[i][j] - matrix_b[i][j])
    matrix_diff.append(row)

print("Diff of Matrix using list:  ", matrix_sum)


# Using numpy array
matrix_diff = matrix_a_np - matrix_b_np
print("Diff of Matrix using '-':   ", matrix_diff)

matrix_diff = np.subtract(matrix_a_np, matrix_b_np)
print("Diff of Matrix using subtract: ", matrix_diff)

Diff of Matrix using list:   [[ 3  6  9]
 [12 15 18]
 [21 24 27]]
Diff of Matrix using '-':    [[-1 -2 -3]
 [-4 -5 -6]
 [-7 -8 -9]]
Diff of Matrix using subtract:  [[-1 -2 -3]
 [-4 -5 -6]
 [-7 -8 -9]]


In [14]:
     # Transpose
# Using List
matrix_tps = []
# for i in range(len(matrix_a)):
#     row = []
#     for j in range(len(matrix_a[0])):
#         if i < j:
#             matrix_a[i][j], matrix_a[j][i] = matrix_a[j][i], matrix_a[i][j]
#         row.append(matrix_a[i][j])
#     matrix_tps.append(row)

print("Transpose of matrix: ", matrix_tps)

# Using numpy array

matrix_tps = matrix_a_np.T
print("Transpose of matrix using 'T': ", matrix_tps)

matrix_tps = np.transpose(matrix_a_np)
print("Transpose of matrix using transpose(): ", matrix_tps)

Transpose of matrix:  []
Transpose of matrix using 'T':  [[1 4 7]
 [2 5 8]
 [3 6 9]]
Transpose of matrix using transpose():  [[1 4 7]
 [2 5 8]
 [3 6 9]]


In [15]:
# Multiplication
# Using list
matrix_pdt = []
for i in range(len(matrix_a)):
    row = []
    for j in range(len(matrix_b[0])):
        product_sum = 0  
        for k in range(len(matrix_b)):
            product_sum += matrix_a[i][k] * matrix_b[k][j]
        row.append(product_sum)
    matrix_pdt.append(row)

print("Product of matrix using List:    ", matrix_pdt)

# Using numpy array
matrix_pdt = matrix_a_np @ matrix_b_np
print("Product of matrix using '@':    ", matrix_pdt)

matrix_pdt = np.dot(matrix_a_np, matrix_b_np)
print("Product of matrix using dot():    ", matrix_pdt)

Product of matrix using List:     [[60, 72, 84], [132, 162, 192], [204, 252, 300]]
Product of matrix using '@':     [[ 60  72  84]
 [132 162 192]
 [204 252 300]]
Product of matrix using dot():     [[ 60  72  84]
 [132 162 192]
 [204 252 300]]


In [28]:
# Determinent
matrix_a = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 10]
]

def determinent(matrix):
    n = len(matrix)

    if n == 1:
        return matrix[0][0]
    elif n == 2:
        return (matrix[0][0]*matrix[1][1] - matrix[0][1]*matrix[1][0])
    else:
        det = 0
        for column in range(n):
            minor = [[
                matrix[i][j] for j in range(n) if j!= column]
                     for i in range(1,n)
                    ]
            sign = (-1)**column
            det += sign * matrix[0][column] * determinent(minor)
        return det

det = determinent(matrix_a)
print("Determinent using List:  ", det)


# Using numpy array
det = np.linalg.det(matrix_a)
print("Determinent using det(): ", det)

Determinent using List:   -3
Determinent using det():  -3.000000000000001


In [34]:
# Identity matrix

matrix_a = [
    [4, 7, 2],
    [3, 6, 1],
    [2, 5, 1]
]

def inverse_matrix(matrix):
    n = len(matrix)

    id_matrix = [[float(i==j) for i in range(n)]for j in range(n)]

    mat = [row[:] for row in matrix]

    for i in range(n):
        diag = mat[i][i]
        if diag == 0:
            raise ValueError("Singular no inverse")

        for j in range(n):
            mat[i][j] /= diag
            id_matrix[i][j] /= diag

        for k in range(n):
            if k != i:
                factor = mat[k][i]
                for j in range(n):
                    mat[k][j] -= factor * mat[i][j]
                    id_matrix[k][j] -= factor * id_matrix[i][j]
    return id_matrix


matrix_id = inverse_matrix(matrix_a)
print("Inverse using list: ")
for row in matrix_id:
    print(row)

# Using numpy array
matrix_a_np = np.array(matrix_a)

matrix_id = np.linalg.inv(matrix_a_np)
print(matrix_id)

Inverse using list: 
[0.3333333333333335, 1.0, -1.6666666666666665]
[-0.33333333333333337, 0.0, 0.6666666666666666]
[1.0, -2.0, 1.0]
[[ 0.33333333  1.         -1.66666667]
 [-0.33333333  0.          0.66666667]
 [ 1.         -2.          1.        ]]


In [46]:
# Eigen values and Eigen vectors


# for 2x2 matrix
import math

def find_eigen(matrix):
    a, b = matrix[0]
    c, d = matrix[1]

    trace = a + d             #  Sum of diagonals
    determinent = a*d - b*c   # Tells if eigen value is real or complex

    descriminant = trace**2 - 4*determinent

    if descriminant < 0:
        return "Complex value....."

    sqrt_disc = math.sqrt(descriminant)

    lambda1 = (trace + sqrt_disc)/2
    lambda2 = (trace - sqrt_disc)/2

    eigenvalues = [lambda1, lambda2]

    eigenvectors = []
    for lam in eigenvalues:
        A_minus_lambda_I = [
            [a-lam, b],
            [c, d-lam]
        ]

        if b != 0:
            x = -(a-lam) / b
            eigenvectors.append([x, 1])
        elif c != 0:
            y = -(d-lam) / c
            eigenvectors.append([1,y])
        else:
            eigenvectors.append([1,0])
            
    return eigenvalues, eigenvectors


A = [[8, 2],[2, 6]]

eigenvalues, eigenvectors = find_eigen(A)

print("Eigenvalues:  ", eigenvalues)
print("Eigenvectors: ")
for v in eigenvectors:
    print(v)

Eigenvalues:   [9.23606797749979, 4.76393202250021]
Eigenvectors: 
[0.6180339887498949, 1]
[-1.618033988749895, 1]
